cliente/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('login/', views.login, name="login"),
    path('logout', views.logout, name="logout"),    
    path('register_client/', views.register_client, name="register_client"),
    path('register_client_info/', views.register_client_info, name='register_client_info'),
    path('register_pet/', views.register_pet, name="register_pet"),
    path('listar_pets/', views.listar_pets, name='listar_pets'),
    path('edit_pet/<int:pet_id>/', views.edit_pet, name='edit_pet'),
    path('delete_pet/<int:pet_id>/', views.delete_pet, name='delete_pet'),
    path('confirm-email/<uidb64>/<token>/', views.confirm_email, name='confirm_email'),
]

love_pets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('cliente.urls')),    
    path('agenda/', include('agendamento.urls')),
]

cliente/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    choices_cargo = (('W', 'Owner'), ('C', 'Client'))
    cargo = models.CharField(max_length=1, choices=choices_cargo)
    is_active = models.BooleanField(default=False) 

class Client(models.Model):
    cpf = models.CharField(max_length=14)
    telefone = models.CharField(max_length=15, blank=False, null=False)
    choices_sexo = (('M', 'Masculino'), ('F', 'Feminino'))
    sexo = models.CharField(max_length=1, choices=choices_sexo)
    cep = models.CharField(max_length=11)
    choices_estado = (
        ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'),
        ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'),
        ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')
    )
    estado = models.CharField(max_length=2, choices=choices_estado, default='SP', blank=False, null=False)
    cidade = models.CharField(max_length=100, blank=False, null=False)
    bairro = models.CharField(max_length=100, blank=False, null=False)
    numero = models.CharField(max_length=10, blank=False, null=False)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    user = models.OneToOneField(Users, on_delete=models.CASCADE)



class Animal(models.Model):
    nome = models.CharField(max_length=50)
    raca = models.CharField(max_length=25)
    choices_pelo = (('L', 'Longo'),
                     ('C', 'Curto'))
    tipo_pelo = models.CharField(max_length=1, choices=choices_pelo, default='C')
    choices_porte = (('P', 'Pequeno'),
                     ('M', 'Medio'),
                     ('G', 'Grande'))
    porte = models.CharField(max_length=1, choices=choices_porte, default='P')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    ativo = models.BooleanField(default=True) 

    def __str__(self):
        return self.nome

cliente/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms  
from .models import Users, Client, Animal

class UserChangeForm(auth_forms.UserChangeForm):
    class Meta(auth_forms.UserChangeForm.Meta):
        model = Users

class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = Users

class UserForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['cpf', 'telefone', 'sexo', 'cep', 'estado', 'cidade', 'bairro', 'numero', 'complemento']
        widgets = {
            'cpf': forms.TextInput(attrs={'class': 'form-control', 'id': 'cpf'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'id': 'telefone'}),
            'sexo': forms.Select(attrs={'class': 'form-control'}),
            'cep': forms.TextInput(attrs={'class': 'form-control', 'id': 'cep'}),
            'estado': forms.Select(attrs={'class': 'form-control', 'id': 'estado'}),
            'cidade': forms.TextInput(attrs={'class': 'form-control', 'id': 'cidade'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control', 'id': 'bairro'}),
            'numero': forms.TextInput(attrs={'class': 'form-control'}),
            'complemento': forms.TextInput(attrs={'class': 'form-control', 'id': 'complemento'}),
        }

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['cep'].required = True
        self.fields['complemento'].required = True
        self.fields['cidade'].required = False
        self.fields['estado'].required = False
        self.fields['bairro'].required = False
        self.fields['numero'].required = False


class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ['nome', 'raca', 'tipo_pelo', 'porte']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'raca': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_pelo': forms.Select(attrs={'class': 'form-control'}),
            'porte': forms.Select(attrs={'class': 'form-control'}),
        }

cliente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Animal, Client
from agendamento.models import Agendamento
from django.contrib import messages
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ClientForm, AnimalForm
from django.core.mail import EmailMultiAlternatives
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model
from django.http import HttpResponse


def inicio(request):
    return render(request, '../templates/inicio.html')

def login(request):
    return render(request, '../templates/login.html')


# FUNCOES ---> CADASTRO E CONFIRMACAO DE USUARIO
User = get_user_model()

def register_client(request):
    if request.method == "GET":        
        return render(request, 'register_client.html')
    
    if request.method == "POST":
        nome = request.POST.get('nome')
        sobrenome = request.POST.get('sobrenome')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirma_senha = request.POST.get('confirma_senha')

        user = User.objects.filter(email=email)

        if user.exists():            
            messages.add_message(request, messages.ERROR, 'E-mail já cadastrado em outro momento')
            return redirect(reverse('register_client'))                
        elif senha != confirma_senha:
            messages.add_message(request, messages.ERROR, 'As senhas digitadas não conferem')
            return redirect(reverse('register_client'))
        elif senha == '':
            messages.add_message(request, messages.ERROR, 'O campo senha é obrigatório')
            return redirect(reverse('register_client'))
        
        user = User.objects.create_user(
            username=email, 
            email=email, 
            password=senha, 
            first_name=nome, 
            last_name=sobrenome,
            is_active=False,  # Usuário inativo até confirmação do email
            cargo="C"
        )

        send_confirmation_email(user, request)  # Enviar email de confirmação

        messages.add_message(request, messages.SUCCESS, 'Usuário cadastrado com sucesso. Verifique seu email para confirmar o cadastro.')
        return redirect(reverse('login'))


def send_confirmation_email(user, request):
    token = default_token_generator.make_token(user)
    uid = urlsafe_base64_encode(force_bytes(user.pk))  # Não chame .decode() aqui
    confirm_url = reverse('confirm_email', kwargs={'uidb64': uid, 'token': token})
    confirm_link = request.build_absolute_uri(confirm_url)

    subject = 'LOVE PETS - Confirme seu email'
    message = render_to_string('email_confirmation.html', {
        'user': user,
        'confirm_link': confirm_link
    })

    enviar_aviso(subject, message, [user.email])


def confirm_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Email confirmado com sucesso!')
        return redirect('login')
    else:
        messages.error(request, 'Link de confirmação inválido ou expirado.')
        return redirect('register_client')


def enviar_aviso(subject, message, recipient_list):
    from_email = 'victor@emultec.com.br'
    
    # Cria uma mensagem de e-mail alternativa
    email = EmailMultiAlternatives(subject, message, from_email, recipient_list)
    
    # Define o conteúdo HTML da mensagem
    email.attach_alternative(message, "text/html")
    
    # Envia o e-mail
    email.send()
    return HttpResponse("E-mail de aviso enviado com sucesso.")



# FUNCOES ---> LOGIN E LOGOUT
def login(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            # redirect redireciona para a pagina desejada e o reverse tranforma o nome em um URL
            messages.add_message(request, messages.ERROR, 'Usuario ja logado')
            return redirect(reverse('register_client_info')) 
        return render(request, 'login.html')
    elif request.method == "POST": 
        login = request.POST.get('email')
        senha = request.POST.get('senha')

        user = auth.authenticate(username=login, password=senha)

        if not user:
            messages.add_message(request, messages.ERROR, 'Usuario ou senha invalidos')
            return redirect(reverse('login'))
        
        auth.login(request,user)
        messages.add_message(request, messages.SUCCESS, 'Usuario logado com Sucesso')        
        return redirect(reverse('login'))
    
def logout(request):
    request.session.flush()
    messages.add_message(request, messages.WARNING, 'Logout efetuado com sucesso')
    return redirect(reverse('login'))



# FUNCOES ---> INFORMACOES ADICIONAIS CLIENTE 
@login_required
def register_client_info(request):
    try:
        client = Client.objects.get(user=request.user)
    except Client.DoesNotExist:
        client = None

    if request.method == "POST":
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            client = form.save(commit=False)
            if not validar_cpf(client.cpf):
                messages.error(request, 'CPF inválido. Por favor, verifique os dados e tente novamente.')
                return redirect('register_client_info')
            client.user = request.user
            client.save()
            messages.success(request, 'Dados complementares cadastrados com sucesso')
            return redirect('register_client_info')
    else:
        form = ClientForm(instance=client)

    estados_choices = Client._meta.get_field('estado').choices
    sexo_choices = Client._meta.get_field('sexo').choices

    context = {
        'estados_choices': estados_choices,
        'sexo_choices': sexo_choices,
        'form': form,
        'client': client
    }
    return render(request, 'register_client_info.html', context)

def validar_cpf(cpf):
    cpf = ''.join(filter(str.isdigit, cpf))
    
    if len(cpf) != 11:
        return False

    if cpf == cpf[0] * 11:
        return False

    soma = sum(int(cpf[i]) * (10 - i) for i in range(9))
    digito1 = (soma * 10 % 11) % 10

    soma = sum(int(cpf[i]) * (11 - i) for i in range(10))
    digito2 = (soma * 10 % 11) % 10

    return digito1 == int(cpf[9]) and digito2 == int(cpf[10])



# FUNCOES ---> PET 
@login_required
def register_pet(request):
    try:
        client = get_object_or_404(Client, user=request.user)
    except:
        messages.error(request, 'Você precisa registrar suas informações de cliente antes de cadastrar um pet.')
        return redirect('register_client_info')  # Redireciona para a página de registro de informações do cliente

    if request.method == "POST":
        nome_pet = request.POST.get('nome_pet')
        raca = request.POST.get('raca')
        tipo_pelo = request.POST.get('tipo_pelo')
        porte = request.POST.get('porte')

        if not nome_pet or not raca or not tipo_pelo or not porte:
            messages.add_message(request, messages.ERROR, 'Todos os campos são obrigatórios.')
            return redirect(reverse('register_pet'))

        animal = Animal(
            nome=nome_pet,
            raca=raca,
            tipo_pelo=tipo_pelo,
            porte=porte,
            client=client
        )

        animal.save()

        messages.add_message(request, messages.SUCCESS, 'Pet cadastrado com sucesso')
        return redirect(reverse('inicio'))

    choices_pelo = Animal._meta.get_field('tipo_pelo').choices
    choices_porte = Animal._meta.get_field('porte').choices
    context = {
        'choices_pelo': choices_pelo,
        'choices_porte': choices_porte
    }
    return render(request, 'register_pet.html', context)        


@login_required
def listar_pets(request):
    try:
        client = Client.objects.get(user=request.user)
        pets = Animal.objects.filter(client=client, ativo=True)
    except Client.DoesNotExist:
        messages.error(request, 'Cliente não encontrado.')
        return redirect('inicio')

    context = {
        'pets': pets,
    }
    return render(request, 'list_pets.html', context)


@login_required
def edit_pet(request, pet_id):
    try:
        client = Client.objects.get(user=request.user)
    except Client.DoesNotExist:
        messages.error(request, 'Cliente não encontrado.')
        return redirect('inicio')

    animal = get_object_or_404(Animal, id=pet_id, client=client)

    if request.method == 'POST':
        pet_form = AnimalForm(request.POST, instance=animal)

        if pet_form.is_valid():
            pet_form.save()
            messages.success(request, 'Dados do pet atualizados com sucesso!')
            return redirect('listar_pets')
    else:
        pet_form = AnimalForm(instance=animal)

    context = {
        'pet_form': pet_form,
    }
    return render(request, 'edit_pet.html', context)

@login_required
def delete_pet(request, pet_id):
    try:
        client = Client.objects.get(user=request.user)
    except Client.DoesNotExist:
        messages.error(request, 'Cliente não encontrado.')
        return redirect('inicio')

    animal = get_object_or_404(Animal, id=pet_id, client=client)

    if request.method == 'POST':
        if Agendamento.objects.filter(id_animal=animal).exists():            
            animal.ativo = False
            animal.save()
            messages.success(request, 'Pet inativado com sucesso!')
        else:
            animal.delete()

cliente/templates/delete_pet.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
<section class="brand">
    {% if messages %}
        <div id="messages">
            <br>
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="login">
        <h2>Confirmar Exclusão do Pet</h2>
        <h3>Tem certeza de que deseja apagar o pet {{ animal.nome }}?<h3>
        <br>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn-danger">Apagar</button>
            <a href="{% url 'listar_pets' %}" class="btn-success">Cancelar</a>
        </form>
    </div>
</section>
{% endblock %}

cliente/templates/edit_pet.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
<section class="brand">
    {% if messages %}
        <div id="messages">
            <br>
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="login">
        <h2>Editar Cadastro do Pet</h2>
        <form method="POST">
            {% csrf_token %}
            {{ pet_form.as_p }}
            <input type="submit" class="btn-success" value="Atualizar Dados">
        </form>
    </div>
</section>
{% endblock %}

cliente/templates/email_confirmation.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirme seu email</title>
    <style>
        body {
            font-family: 'Open Sans', sans-serif;
            background-color: #F7F8FA;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            padding: 20px 0;
        }
        .header img {
            max-width: 150px;
        }
        .content {
            padding: 20px;
            text-align: center;
        }
        .content h1 {
            color: #FF9900;
        }
        .content p {
            line-height: 1.6;
            margin: 20px 0;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            background-color: #FF9900;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }
        .footer {
            text-align: center;
            padding: 10px;
            font-size: 12px;
            color: #aaa;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <img src="https://lovepetsrc.com.br/static/cliente/img/logo_nav_bar_2.png" alt="Love Pets">
        </div>
        <div class="content">
            <h1>Confirme seu email</h1>
            <p>Olá {{ user.first_name }},</p>
            <p>Obrigado por se cadastrar. Por favor, clique no botão abaixo para confirmar seu email:</p>
            <a href="{{ confirm_link }}" class="button">Confirmar Email</a>
            <p>Se você não se cadastrou, ignore este email.</p>
        </div>
        <div class="footer">
            <p>© 2024 Love Pets. Todos os direitos reservados.</p>
        </div>
    </div>
</body>
</html>

cliente/templates/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block 'home' %}
    {% if messages %}
    <br>
        {% for message in messages %}
            <section>
            <div class="alert {{ message.tags }}"> {{ message }} </div>
        </section>
        {% endfor %}
    {% endif %}

    <section class="home_inicio" id="home">
        <div class="home-text">
            <h1>Estetica Animal<br><span>LOVE PETS</span></h1>
            <p>Onde o amor pelos animais encontra <br> praticidade e qualidade</p>
            {% if user.is_authenticated %}
                <a href="{% url 'criar_agenda' %}" class="btn">Agendar</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

cliente/templates/list_pets.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
<section class="brand">
    {% if messages %}
    <br>
    {% for message in messages %}
    <div class="alert {{ message.tags }}"> {{ message }} </div>
    {% endfor %}
    {% endif %}

    <div class="login">
        <div class="agendamentos">
            <h1><label>Seus Pets</label></h1>
            {% if pets %}
            <div class="table-container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Raça</th>
                            <th>Tipo de Pelo</th>
                            <th>Porte</th>
                            <th>Ações</th>
                            {% endif %}
                            {% if not pets %}
                            <h1>Opss... Parece que não há pets cadastrados</h1>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for pet in pets %}
                        <tr>
                            <td>{{ pet.nome }}</td>
                            <td>{{ pet.raca }}</td>
                            <td>{{ pet.get_tipo_pelo_display }}</td>
                            <td>{{ pet.get_porte_display }}</td>
                            <td>
                                <a href="{% url 'edit_pet' pet.id %}" class="btn btn-success">Editar</a>
                                <a href="{% url 'delete_pet' pet.id %}" class="btn btn-danger">Apagar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <br>
            <br>
            <a href="{% url 'register_pet' %}" class="btn-success">Voltar</a>
        </div>
</section>
{% endblock %}

cliente/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}
<section class="brand"> 
    {% if messages %}
        <div id="messages">
            <br>
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="login">
        <form action="{% url 'login' %}" method="POST">{% csrf_token %}
            <label>ENTRE COM SEU USUÁRIO!</label>
            <br>
            <label>E-mail</label>
            <input type="email" placeholder="Digite seu E-mail...." name="email" class="form-control">
            <br>
            <label>Senha</label>
            <input type="password" placeholder="Digite sua Senha...." name="senha" class="form-control">
            <br>
            <input type="submit" class="btn btn-success" value="Entrar">
        </form>
    </div>
</section>
{% endblock %}

cliente/templates/register_client.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
{% endblock %}

{% block 'body' %}

<section class="brand">   

    {% if messages  %}
    <br>
        {% for message in messages %}
            <div class="alert {{message.tags}}"> {{message}} </div>
        {% endfor %}
    {% endif %}
    

    <div class="login">
        <form action="{% url 'register_client' %}" method="POST">{% csrf_token %}
            <label>CRIE SEU USUÁRIO!</label>
            <br>
            <label>Nome</label>
            <input type="text" placeholder="Digite seu Nome...." name="nome" class="form-control">
            <br>
            <label>Sobrenome</label>
            <input type="text" placeholder="Digite seu Sobrenome...." name="sobrenome" class="form-control">
            <br>
            <label>E-mail</label>
            <input type="email" placeholder="Digite seu E-mail...." name="email" class="form-control">
            <br>
            <label>Senha</label>
            <input type="password" placeholder="Digite seu Senha...." name="senha" class="form-control">
            <br>
            <label>Confirme a senha</label>
            <input type="password" placeholder="Confirme a Senha...." name="confirma_senha" class="form-control">
            <br>
            <input type="submit" class="btn-success" value="Cadastrar">
        </form>
    </div>
</section>

{% endblock %}

cliente/templates/register_client_info.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}

<section class="brand">   

    {% if messages %}
    <br>
        {% for message in messages %}
            <div class="alert {{ message.tags }}"> {{ message }} </div>
        {% endfor %}
    {% endif %}
    
    <div class="login">
        <form action="{% url 'register_client_info' %}" method="POST" id="clientForm">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn-success">
        </form>
    </div>
</section>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- jQuery Mask Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script>
    $(document).ready(function() {
        function initializeMasksAndEvents() {
            $('#cpf').mask('000.000.000-00', {placeholder: '___.___.___-__'});
            $('#telefone').mask('(00) 00000-0000', {placeholder: '(__) _____-____'});
            $('#cep').mask('00000-000', {placeholder: '_____-___'});

            $('#cep').on('blur', function() {
                consultarCEP($(this).val());
            });

            $('#estado').on('change', function() {
                var estado = $(this).val();
                if (estado) {
                    $.getJSON(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/${estado}/municipios`, function(data) {
                        var options = '<option value="">Selecione a Cidade</option>';
                        data.forEach(function(cidade) {
                            options += `<option value="${cidade.nome}">${cidade.nome}</option>`;
                        });
                        $('#cidade').html(options);
                    });
                } else {
                    $('#cidade').html('<option value="">Selecione o Estado primeiro</option>');
                }
            });

            $('#clientForm').on('submit', function(event) {
                var cep = $('#cep').val().replace(/\D/g, '');
                if (cep && cep.length !== 8) {
                    alert("CEP inválido. Por favor, verifique os dados e tente novamente.");
                    event.preventDefault();
                }
            });
        }

        initializeMasksAndEvents();

        function preencherEndereco(data) {
            $('#bairro').val(data.bairro);
            $('#cidade').val(data.localidade);
            $('#estado').val(data.uf);
            $('#complemento').val(data.complemento);
        }

        function consultarCEP(cep) {
            cep = cep.replace(/\D/g, '');
            if (cep !== "") {
                var validacep = /^[0-9]{8}$/;
                if (validacep.test(cep)) {
                    $.getJSON(`https://viacep.com.br/ws/${cep}/json/`, function(data) {
                        if (!("erro" in data)) {
                            preencherEndereco(data);
                        } else {
                            alert("CEP não encontrado.");
                        }
                    });
                } else {
                    alert("Formato de CEP inválido.");
                }
            }
        }

        $.getJSON('https://servicodados.ibge.gov.br/api/v1/localidades/estados', function(data) {
            var options = '<option value="">Selecione o Estado</option>';
            data.forEach(function(estado) {
                options += `<option value="${estado.sigla}">${estado.nome}</option>`;
            });
            $('#estado').html(options);

            // Pré-selecionar o estado atual do cliente
            var selectedEstado = "{{ client.estado|default:'' }}";
            if (selectedEstado) {
                $('#estado').val(selectedEstado).change();
            }
        });
    });
</script>

{% endblock %}

cliente/templates/register_pet.html
{% extends 'base.html' %}
{% load static %}

{% block 'body' %}

<section class="brand">   

    {% if messages %}
    <br>
        {% for message in messages %}
            <div class="alert {{message.tags}}"> {{message}} </div>
        {% endfor %}
    {% endif %}

    <div class="login">
        <form action="{% url 'register_pet' %}" method="POST">{% csrf_token %}
            <br>
            <label>Nome do Pet</label>
            <input type="text" placeholder="Digite o nome do seu pet...." name="nome_pet" class="form-control">
            <br>
            <label>Raça</label>
            <select name="raca" class="form-control">
                <option value="Vira-lata">Vira-lata</option>
                <option value="Shih Tzu">Shih Tzu</option>
                <option value="Yorkshire">Yorkshire</option>
                <option value="Poodle">Poodle</option>
                <option value="Lhasa Apso">Lhasa Apso</option>
                <option value="Buldogue francês">Buldogue francês</option>
                <option value="Pinscher">Pinscher</option>
                <option value="Golden Retriever">Golden Retriever</option>
                <option value="Spitz Alemão">Spitz Alemão</option>
                <option value="Maltês">Maltês</option>
                <option value="Labrador Retriever">Labrador</option>
                <option value="Pastor-alemão">Pastor-alemão</option>
                <option value="Bulldog">Bulldog</option>
                <option value="Beagle">Beagle</option>
                <option value="Rottweiler">Rottweiler</option>
                <option value="Braco alemão de pelo curto">Braco alemão</option>
                <option value="Dachshund">Dachshund</option>
                <option value="Outros">Outros</option>
            </select>
            <br>
            <label>Tipo do pelo</label>
            <select name="tipo_pelo" class="form-control">
                {% for value, display in choices_pelo %}
                    <option value="{{ value }}">{{ display }}</option>
                {% endfor %}
            </select>
            <br>
            <label>Porte</label>
            <select name="porte" class="form-control">
                {% for value, display in choices_porte %}
                    <option value="{{ value }}">{{ display }}</option>
                {% endfor %}
            </select>
            <br>
            <br>
            <input type="submit" class="btn-success" value="Cadastrar">
        </form>
        <a href="{% url 'listar_pets' %}" class="btn-success">Listar Pets</a>
    </div>
</section>

{% endblock %}